# Generated by Django 4.2.23 on 2025-07-04 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('skill1', models.CharField(blank=True, max_length=255, null=True)),
                ('progress1', models.IntegerField(blank=True, null=True)),
                ('skill2', models.CharField(blank=True, max_length=255, null=True)),
                ('progress2', models.IntegerField(blank=True, null=True)),
                ('skill3', models.CharField(blank=True, max_length=255, null=True)),
                ('progress3', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_id', models.CharField(max_length=100)),
                ('rep_name', models.CharField(max_length=100)),
                ('rep_des', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(default=123, max_length=255)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('filedes', models.TextField()),
                ('file', models.FileField(upload_to='repositories/')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repository')),
            ],
        ),
    ]
