# Generated by Django 5.0.6 on 2024-07-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='repositoryowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='library',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='repositoryowner',
            name='repository',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='RepositoryOwner',
        ),
    ]
