# Generated by Django 5.0.6 on 2024-07-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_repository_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='group',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
