# Generated by Django 5.0.6 on 2024-07-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_repository_group_delete_file_delete_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.CharField(max_length=100)),
                ('repository_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
