# Generated by Django 5.0.6 on 2024-07-07 20:53

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='description',
            new_name='rep_des',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='repository_id',
            new_name='rep_id',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='repository_name',
            new_name='rep_name',
        ),
        migrations.AddField(
            model_name='repository',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=app.models.upload_location),
            preserve_default=False,
        ),
    ]
