# Generated by Django 5.0.6 on 2024-07-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_description_repository_rep_des_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
