# Generated by Django 5.0.6 on 2024-07-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_repository_file_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
