# Generated by Django 5.0.6 on 2024-07-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_userprofile_bio_alter_userprofile_hobbies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
