# Generated by Django 5.0.6 on 2024-07-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_profile_bio_alter_profile_hobbies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progress1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progress2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progress3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.AddField(
            model_name='profile',
            name='groupid',
            field=models.CharField(default=123, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('skill1', models.CharField(blank=True, max_length=255, null=True)),
                ('progress1', models.IntegerField(blank=True, null=True)),
                ('skill2', models.CharField(blank=True, max_length=255, null=True)),
                ('progress2', models.IntegerField(blank=True, null=True)),
                ('skill3', models.CharField(blank=True, max_length=255, null=True)),
                ('progress3', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
